
#x=int(input())

#try:     
#    print(x)
#except:      #Ще се принтира ако горния принт не може да бъде изпълнен, ако ли горния може да се изпълни няма да се принтира долния принт
#    print("An exception occurred")

#x=3
#try:
#    print(x)
#except NameError:    #Така даваме да следи за точно определ ексепшън 
#    print("Variable x is not defined")
#except:
#    print("Something else went wrong")


#try:
#    print("Hello")
#except:
#    print("Something went wrong")
#else:    #Ще го изпълни ако не е хванат ексепшънът
#    print("Nothing went wrong")